# APP CONFIGURATION
# Updates the package name and display name for your app

# Run: 'flutter pub run flutter_application_id:main'

flutter_application_id:
  android:
    id: "com.nylo.dev"
    name: "Nylo"
  ios:
    id: "com.nylo.dev"
    name: "Nylo"